# Generated by Django 3.1.6 on 2021-02-07 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='order',
            new_name='userList',
        ),
    ]
